name: 'Ansible Playbook Runner'
description: 'Run an Ansible playbook'

branding:
  icon: arrow-up-circle
  color: black

inputs:
  inventory:
    description: 'Ansible inventory to use'
    required: true
    default: inventory.yml
  playbook:
    description: 'Ansible playbook to run'
    required: true
    default: playbook.yml
runs:
  using: docker
  image: docker://mrskug/actions-ansible
  args:
    - ${{ inputs.inventory }}
    - ${{ inputs.playbook }}
